// Generated by "save tags to file" in the CV organizer.
// Commit and push this file to make tag/star data live on the main site.
window.ORG_DATA = {
  "BLARP!": {
    "tags": [
      "vr",
      "games"
    ],
    "stars": 4
  },
  "L U N E": {
    "tags": [
      "vr",
      "games",
      "art",
      "music"
    ],
    "stars": 5
  },
  "Delila's Gift": {
    "tags": [
      "vr",
      "writing",
      "art",
      "experiments"
    ],
    "stars": 4
  },
  "Warka Flarka Flim Flam": {
    "tags": [
      "games",
      "vr"
    ],
    "stars": 2
  },
  "My Lil' Donut": {
    "tags": [
      "vr",
      "games",
      "art",
      "tool"
    ],
    "stars": 4
  },
  "Audio Forager": {
    "tags": [
      "art",
      "tool",
      "vr",
      "research"
    ],
    "stars": 3
  },
  "Jellyfish Island": {
    "tags": [
      "art",
      "experiments",
      "vr"
    ],
    "stars": 2
  },
  "Saturnalia": {
    "tags": [
      "games",
      "work"
    ],
    "stars": 3
  },
  "Wanderstop": {
    "tags": [
      "games",
      "work"
    ],
    "stars": 3
  },
  "Jónsi: SAD": {
    "tags": [
      "art",
      "music",
      "work"
    ],
    "stars": 5
  },
  "Jónsi: Vox": {
    "tags": [
      "art",
      "music",
      "work"
    ],
    "stars": 5
  },
  "Hayden Dunham: Transmutation": {
    "tags": [
      "art",
      "music",
      "work"
    ],
    "stars": 3
  },
  "IM ‖ MATERIA": {
    "tags": [
      "art",
      "games",
      "open source",
      "tool"
    ],
    "stars": 4
  },
  "NEXUS": {
    "tags": [
      "art",
      "web",
      "music"
    ],
    "stars": 2
  },
  "Currents Virtual Festival": {
    "tags": [
      "art",
      "music",
      "web"
    ],
    "stars": 2
  },
  "Teknopolis": {
    "tags": [
      "web",
      "vr",
      "art"
    ],
    "stars": 2
  },
  "Spatial Reality / Steps": {
    "tags": [
      "vr",
      "art"
    ],
    "stars": 4
  },
  "Olafur Eliasson: Rainbow": {
    "tags": [
      "vr",
      "art",
      "work"
    ],
    "stars": 5
  },
  "Float Museum": {
    "tags": [
      "art",
      "vr"
    ],
    "stars": 3
  },
  "The Art of VR": {
    "tags": [
      "art",
      "vr"
    ],
    "stars": 1
  },
  "Life of Us": {
    "tags": [
      "art",
      "work",
      "vr"
    ],
    "stars": 4
  },
  "H E N G E": {
    "tags": [
      "art",
      "web",
      "music"
    ],
    "stars": 4
  },
  "3D Web Fest": {
    "tags": [
      "art",
      "web"
    ],
    "stars": 1
  },
  "FILF": {
    "tags": [
      "animation",
      "work"
    ],
    "stars": 1
  },
  "ENOUGH": {
    "tags": [
      "writing",
      "art",
      "web",
      "music",
      "open source"
    ],
    "stars": 5
  },
  "Light": {
    "tags": [
      "web",
      "music",
      "art",
      "writing"
    ],
    "stars": 4
  },
  "NoThing": {
    "tags": [
      "web",
      "music",
      "art",
      "writing"
    ],
    "stars": 4
  },
  "GROWTH": {
    "tags": [
      "web",
      "music",
      "art"
    ],
    "stars": 3
  },
  "Lazarus Under Lights": {
    "tags": [
      "art",
      "animation",
      "web",
      "music",
      "work"
    ],
    "stars": 4
  },
  "Prismatic Realities": {
    "tags": [
      "art",
      "web",
      "writing",
      "talk"
    ],
    "stars": 4
  },
  "PLAID — Digging Remedy": {
    "tags": [
      "web",
      "music",
      "art",
      "work"
    ],
    "stars": 3
  },
  "PLAID — Maru / Polymer": {
    "tags": [
      "art",
      "music",
      "web",
      "work"
    ],
    "stars": 5
  },
  "TAJ — Adobe Design AYA": {
    "tags": [
      "work",
      "art",
      "web"
    ],
    "stars": 1
  },
  "Quoi — Avalon Emerson": {
    "tags": [
      "work",
      "art",
      "music",
      "web"
    ],
    "stars": 3
  },
  "Insidious Rising": {
    "tags": [
      "work",
      "web",
      "research"
    ],
    "stars": 2
  },
  "Beyond": {
    "tags": [
      "web",
      "music",
      "art",
      "animation"
    ],
    "stars": 5
  },
  "Rainbow Membrane": {
    "tags": [
      "art",
      "web",
      "vr"
    ],
    "stars": 3
  },
  "Universe of Sound": {
    "tags": [
      "art",
      "music",
      "web"
    ],
    "stars": 5
  },
  "Fall Sketches": {
    "tags": [
      "art",
      "music",
      "web"
    ],
    "stars": 4
  },
  "L-U-N-E (web version)": {
    "tags": [
      "art",
      "music",
      "web"
    ],
    "stars": 5
  },
  "Prism Simulations": {
    "tags": [
      "art",
      "writing",
      "talk",
      "web"
    ],
    "stars": 5
  },
  "Hold Me": {
    "tags": [
      "art",
      "music",
      "web"
    ],
    "stars": 2
  },
  "Pulse": {
    "tags": [
      "art",
      "music",
      "web",
      "games"
    ],
    "stars": 4
  },
  "Needs": {
    "tags": [
      "art",
      "music",
      "web"
    ],
    "stars": 2
  },
  "Moire No Future": {
    "tags": [
      "art",
      "work",
      "music",
      "web",
      "games"
    ],
    "stars": 1
  },
  "AFK": {
    "tags": [
      "art",
      "work",
      "music",
      "web"
    ],
    "stars": 4
  },
  "Drive": {
    "tags": [
      "art",
      "music",
      "web",
      "experiments"
    ],
    "stars": 2
  },
  "Dotter": {
    "tags": [
      "music",
      "web",
      "experiments",
      "art"
    ],
    "stars": 2
  },
  "Max Weisel portfolio": {
    "tags": [
      "work",
      "art",
      "music",
      "web"
    ],
    "stars": 3
  },
  "gpu Curl Meshes": {
    "tags": [
      "art",
      "experiments",
      "music",
      "web"
    ],
    "stars": 1
  },
  "Shiny": {
    "tags": [
      "experiments",
      "music",
      "web"
    ],
    "stars": 1
  },
  "Weird Kids": {
    "tags": [
      "web",
      "experiments",
      "art"
    ],
    "stars": 1
  },
  "Saturn Strobe": {
    "tags": [
      "art",
      "experiments",
      "music",
      "web"
    ],
    "stars": 3
  },
  "NVScene invite": {
    "tags": [
      "art",
      "experiments",
      "animation",
      "music",
      "web",
      "work"
    ],
    "stars": 4
  },
  "huldra": {
    "tags": [
      "music",
      "web",
      "experiments",
      "art"
    ],
    "stars": 2
  },
  "diamonds": {
    "tags": [
      "experiments",
      "music",
      "web",
      "art"
    ],
    "stars": 1
  },
  "gooey gpu gem": {
    "tags": [
      "art",
      "experiments",
      "music",
      "web",
      "work"
    ],
    "stars": 1
  },
  "ML-Fellowship landing": {
    "tags": [
      "experiments",
      "web",
      "writing"
    ],
    "stars": 1
  },
  "Stellar Nursery (Nebula)": {
    "tags": [
      "experiments",
      "art",
      "music",
      "web",
      "tool"
    ],
    "stars": 2
  },
  "Sound Object Project": {
    "tags": [
      "art",
      "experiments",
      "music",
      "web"
    ],
    "stars": 3
  },
  "Sol": {
    "tags": [
      "games",
      "music",
      "web",
      "art"
    ],
    "stars": 3
  },
  "Come Ballooning (AVBEATS)": {
    "tags": [
      "art",
      "music",
      "web",
      "tool"
    ],
    "stars": 0
  },
  "Cabbibo Set": {
    "tags": [
      "art",
      "web",
      "writing"
    ],
    "stars": 3
  },
  "Julia Set": {
    "tags": [
      "art",
      "web"
    ],
    "stars": 1
  },
  "Mutual Core — Björk (fan site)": {
    "tags": [
      "experiments",
      "music",
      "web",
      "games",
      "art"
    ],
    "stars": 1
  },
  "Holy Other — We Over (fan site)": {
    "tags": [
      "experiments",
      "music",
      "web",
      "art"
    ],
    "stars": 1
  },
  "dannyelfman.com": {
    "tags": [
      "work",
      "web",
      "music"
    ],
    "stars": 4
  },
  "Recursion": {
    "tags": [
      "games",
      "web",
      "music",
      "art"
    ],
    "stars": 4
  },
  "ARQUA!": {
    "tags": [
      "music",
      "ar",
      "games",
      "art",
      "work"
    ],
    "stars": 5
  },
  "Face! Plant!": {
    "tags": [
      "ar",
      "music",
      "art"
    ],
    "stars": 5
  },
  "AR Face Tracking — Facestrument": {
    "tags": [
      "experiments",
      "ar"
    ],
    "stars": 1
  },
  "AR with Markers": {
    "tags": [
      "experiments",
      "ar"
    ],
    "stars": 1
  },
  "Forward Facing AR": {
    "tags": [
      "experiments",
      "ar"
    ],
    "stars": 1
  },
  "Human Segmentation": {
    "tags": [
      "experiments",
      "ar"
    ],
    "stars": 1
  },
  "Skull Island": {
    "tags": [
      "experiments",
      "ar"
    ],
    "stars": 1
  },
  "Shattering Reality": {
    "tags": [
      "experiments",
      "ar"
    ],
    "stars": 1
  },
  "Looking Glass — Dreams Shader Set": {
    "tags": [
      "work",
      "art",
      "ar",
      "web",
      "animation"
    ],
    "stars": 2
  },
  "Looking Glass — WebGL Goo Ball": {
    "tags": [
      "work",
      "art",
      "animation",
      "web",
      "ar"
    ],
    "stars": 2
  },
  "Magic Leap — Depth Scanner": {
    "tags": [
      "experiments",
      "ar"
    ],
    "stars": 2
  },
  "Magic Leap — In World Sliders": {
    "tags": [
      "experiments",
      "ar"
    ],
    "stars": 2
  },
  "Magic Leap — Catenaries": {
    "tags": [
      "experiments",
      "ar"
    ],
    "stars": 4
  },
  "Responsive Bridge Design": {
    "tags": [
      "ar",
      "experiments",
      "research"
    ],
    "stars": 5
  },
  "Painting Density → Mesh": {
    "tags": [
      "experiments",
      "ar",
      "research",
      "tool"
    ],
    "stars": 2
  },
  "Paint Vector Field → Blow": {
    "tags": [
      "experiments",
      "ar",
      "research",
      "tool"
    ],
    "stars": 2
  },
  "Arbitrary Caustics": {
    "tags": [
      "experiments",
      "research"
    ],
    "stars": 2
  },
  "3D Fluid Sim with Isosurface": {
    "tags": [
      "experiments",
      "research"
    ],
    "stars": 2
  },
  "Fish Food": {
    "tags": [
      "animation",
      "music",
      "art"
    ],
    "stars": 5
  },
  "40 Fables: Sun and Wind": {
    "tags": [
      "animation",
      "music",
      "art"
    ],
    "stars": 3
  },
  "Ripplings — Silver Lake Shorts": {
    "tags": [
      "animation",
      "music",
      "art"
    ],
    "stars": 3
  },
  "SOPHIE — FACESHOPPING": {
    "tags": [
      "animation",
      "music",
      "art",
      "work"
    ],
    "stars": 5
  },
  "Finn Keane — Careless": {
    "tags": [
      "animation",
      "music",
      "art",
      "work"
    ],
    "stars": 5
  },
  "Hyd — Fallen Angel": {
    "tags": [
      "animation",
      "music",
      "art",
      "work"
    ],
    "stars": 4
  },
  "Halogen Halos — Leah's BF": {
    "tags": [
      "animation",
      "music",
      "art",
      "work"
    ],
    "stars": 3
  },
  "Pauline Anna Strom — Quiet Joy": {
    "tags": [
      "art",
      "work",
      "animation",
      "music"
    ],
    "stars": 3
  },
  "Pauline Anna Strom — Cult of Isis": {
    "tags": [
      "art",
      "work",
      "animation",
      "music"
    ],
    "stars": 4
  },
  "Alex Somers — When You Wish Upon A Death Star": {
    "tags": [
      "art",
      "work",
      "animation",
      "music"
    ],
    "stars": 3
  },
  "Galen Tipton / Diana Starshine — Sensory Bath": {
    "tags": [
      "art",
      "work",
      "animation",
      "music"
    ],
    "stars": 3
  },
  "Cecile Believe": {
    "tags": [
      "animation",
      "music",
      "work",
      "art"
    ],
    "stars": 3
  },
  "Hyd": {
    "tags": [
      "animation",
      "music",
      "work",
      "art"
    ],
    "stars": 3
  },
  "Finn Keane": {
    "tags": [
      "work",
      "animation",
      "music",
      "art"
    ],
    "stars": 4
  },
  "Frost Children": {
    "tags": [
      "work",
      "art",
      "animation",
      "music"
    ],
    "stars": 3
  },
  "Lil Data": {
    "tags": [
      "work",
      "art",
      "animation",
      "music"
    ],
    "stars": 2
  },
  "Fake and Gay": {
    "tags": [
      "art",
      "experiments",
      "animation",
      "music",
      "work"
    ],
    "stars": 2
  },
  "SKSKSKS": {
    "tags": [
      "art",
      "experiments",
      "animation",
      "music"
    ],
    "stars": 2
  },
  "Easyfun Viz": {
    "tags": [
      "art",
      "animation",
      "music"
    ],
    "stars": 2
  },
  "Makk Mikkeal": {
    "tags": [
      "art",
      "animation",
      "music",
      "experiments"
    ],
    "stars": 2
  },
  "BIB PIT .EXE": {
    "tags": [
      "art",
      "animation",
      "games",
      "music"
    ],
    "stars": 5
  },
  "Bee Two Bee": {
    "tags": [
      "art",
      "animation",
      "games",
      "music"
    ],
    "stars": 5
  },
  "Ripplings 2 / Silver Lake Shorts / Spectra": {
    "tags": [
      "art",
      "animation",
      "games",
      "music"
    ],
    "stars": 2
  },
  "Lil Data × Cabbibo live": {
    "tags": [
      "art",
      "animation",
      "games",
      "music"
    ],
    "stars": 3
  },
  "CEREBRO": {
    "tags": [
      "art",
      "experiments",
      "games"
    ],
    "stars": 3
  },
  "Goo Ball V1": {
    "tags": [
      "experiments",
      "art",
      "games"
    ],
    "stars": 3
  },
  "Toon Sketch Shader Pack": {
    "tags": [
      "art",
      "experiments",
      "games",
      "tool"
    ],
    "stars": 3
  },
  "Fantasy Light": {
    "tags": [
      "art",
      "experiments",
      "games",
      "tool"
    ],
    "stars": 3
  },
  "Fantasy Crystals": {
    "tags": [
      "art",
      "experiments",
      "games",
      "tool"
    ],
    "stars": 4
  },
  "Fantasy Tree": {
    "tags": [
      "art",
      "experiments",
      "games",
      "tool"
    ],
    "stars": 3
  },
  "Magic Curve": {
    "tags": [
      "art",
      "experiments",
      "games",
      "tool"
    ],
    "stars": 4
  },
  "Skinned Mesh Particle Emitter": {
    "tags": [
      "art",
      "experiments",
      "games",
      "tool"
    ],
    "stars": 3
  },
  "Cabbibos Play Pack": {
    "tags": [
      "art",
      "experiments",
      "vr",
      "games"
    ],
    "stars": 4
  },
  "blarp2D": {
    "tags": [
      "games",
      "art"
    ],
    "stars": 4
  },
  "Moon Ball": {
    "tags": [
      "games",
      "art",
      "experiments"
    ],
    "stars": 3
  },
  "PhysicsRenderer": {
    "tags": [
      "open source",
      "web",
      "research"
    ],
    "stars": 5
  },
  "glsl-curl-noise": {
    "tags": [
      "web",
      "open source"
    ],
    "stars": 3
  },
  "enough": {
    "tags": [
      "web",
      "open source",
      "games",
      "art"
    ],
    "stars": 3
  },
  "IMMATERIA": {
    "tags": [
      "art",
      "games",
      "open source"
    ],
    "stars": 4
  },
  "Text": {
    "tags": [
      "art",
      "web",
      "open source",
      "research"
    ],
    "stars": 5
  },
  "ShaderLoader": {
    "tags": [
      "web",
      "open source"
    ],
    "stars": 5
  },
  "FloatyText": {
    "tags": [
      "art",
      "experiments",
      "games",
      "open source"
    ],
    "stars": 2
  },
  "Velocity Field Interaction for Free-Space Gesture Interface and Control": {
    "tags": [
      "writing",
      "research",
      "work"
    ],
    "stars": 5
  },
  "User-Defined Virtual Interaction Space and Manipulation of Virtual Configuration": {
    "tags": [
      "writing",
      "research",
      "work"
    ],
    "stars": 3
  },
  "User-Defined Virtual Interaction Space and Manipulation of Virtual Cameras": {
    "tags": [
      "writing",
      "research",
      "work"
    ],
    "stars": 3
  },
  "SDF Tutorial 1: box & balloon": {
    "tags": [
      "writing",
      "open source",
      "web"
    ],
    "stars": 4
  },
  "impact": {
    "tags": [
      "open source",
      "web",
      "art"
    ],
    "stars": 3
  },
  "Sanctuary": {
    "tags": [
      "open source",
      "web",
      "art"
    ],
    "stars": 1
  },
  "prism: light becoming": {
    "tags": [
      "open source",
      "web",
      "art"
    ],
    "stars": 2
  },
  "Connor Collab 1": {
    "tags": [
      "open source",
      "web",
      "art"
    ],
    "stars": 1
  },
  "Connor Collab 2": {
    "tags": [
      "open source",
      "web",
      "art"
    ],
    "stars": 1
  },
  "Shade-a-Day series": {
    "tags": [
      "open source",
      "web",
      "experiments"
    ],
    "stars": 2
  },
  "The Anatomy of a Jellyfish": {
    "tags": [
      "writing",
      "web"
    ],
    "stars": 5
  },
  "10 Quick Things I've Learned in VR": {
    "tags": [
      "writing",
      "vr",
      "web"
    ],
    "stars": 3
  },
  "Games: A Primer for VR": {
    "tags": [
      "writing",
      "web",
      "vr"
    ],
    "stars": 3
  },
  "Math, Nature and Thievery": {
    "tags": [
      "web",
      "writing",
      "talk"
    ],
    "stars": 3
  },
  "Discovering our Prismatic Reality": {
    "tags": [
      "web",
      "writing",
      "talk"
    ],
    "stars": 3
  },
  "Finding (and Making) Your Happy Place": {
    "tags": [
      "web",
      "writing",
      "talk"
    ],
    "stars": 3
  },
  "From Objects to Scenes to Stories": {
    "tags": [
      "writing",
      "talk"
    ],
    "stars": 3
  },
  "ENOUGH — An Interactive Storybook": {
    "tags": [
      "web",
      "music",
      "writing",
      "talk"
    ],
    "stars": 2
  },
  "Dynamicland at Eyeo": {
    "tags": [
      "research",
      "talk",
      "writing"
    ],
    "stars": 5
  },
  "Real Time is Now": {
    "tags": [
      "writing",
      "web",
      "talk"
    ],
    "stars": 3
  },
  "Experimental Gameplay Workshop (EGW)": {
    "tags": [
      "talk",
      "vr",
      "games"
    ],
    "stars": 3
  },
  "Experimental Games Showcase (ExGS)": {
    "tags": [
      "games",
      "talk"
    ],
    "stars": 3
  },
  "Art and VR at Sotheby's": {
    "tags": [
      "vr",
      "talk"
    ],
    "stars": 1
  },
  "AWE XR speaker": {
    "tags": [
      "vr",
      "talk"
    ],
    "stars": 1
  },
  "Unity — VR Artist in Residence": {
    "tags": [
      "work",
      "art",
      "vr"
    ],
    "stars": 3
  },
  "Adobe — AR Residency": {
    "tags": [
      "work",
      "art",
      "ar"
    ],
    "stars": 2
  },
  "Google — Tilt Brush Artist in Residence": {
    "tags": [
      "work",
      "art",
      "vr"
    ],
    "stars": 4
  },
  "Dynamicland": {
    "tags": [
      "art",
      "experiments",
      "research"
    ],
    "stars": 5
  },
  "Viacom NEXT": {
    "tags": [
      "experiments",
      "art",
      "vr",
      "ar",
      "research",
      "work",
      "games"
    ],
    "stars": 4
  },
  "ENOUGH — FWA Site of the Day": {
    "tags": [
      "web",
      "music",
      "art",
      "games",
      "writing"
    ],
    "stars": 2
  },
  "ENOUGH — FWA Site of the Month": {
    "tags": [
      "web",
      "music",
      "art",
      "games",
      "writing"
    ],
    "stars": 2
  },
  "ENOUGH — Adobe Cutting Edge Award": {
    "tags": [
      "art",
      "music",
      "web",
      "games",
      "writing"
    ],
    "stars": 2
  },
  "ENOUGH — IGF Nuovo Award Honorable Mention": {
    "tags": [
      "games",
      "music",
      "web",
      "writing",
      "art"
    ],
    "stars": 4
  },
  "ENOUGH — AWWWARDS Site of the Year Nomination": {
    "tags": [
      "art",
      "games",
      "music",
      "web",
      "writing"
    ],
    "stars": 3
  },
  "Cabbibo.com — FWA Site of the Day": {
    "tags": [
      "art",
      "games",
      "music",
      "web"
    ],
    "stars": 2
  },
  "Float Museum — Official Selection, SFMoMA": {
    "tags": [
      "art",
      "music",
      "games",
      "vr"
    ],
    "stars": 2
  },
  "L U N E — Official Selection, Teknopolis": {
    "tags": [
      "art",
      "vr",
      "music",
      "games"
    ],
    "stars": 2
  },
  "H E N G E — Official Selection, MUTEK": {
    "tags": [
      "art",
      "web",
      "music"
    ],
    "stars": 2
  },
  "BE A BIRD": {
    "tags": [
      "games",
      "art"
    ],
    "stars": 4
  },
  "BLORP!": {
    "tags": [
      "games",
      "vr",
      "art"
    ],
    "stars": 2
  },
  "A.V.V. / AVDJ": {
    "tags": [
      "games",
      "music",
      "art"
    ],
    "stars": 3
  },
  "Snow Angel": {
    "tags": [
      "games",
      "writing",
      "art"
    ],
    "stars": 2
  }
};
